project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "!projects/assets/"
  resources:
    - "projects/assets/**"

website:
  title: "Sean Ryan"
  navbar:
    left:
      - href: index.qmd
        text: Work
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/StrokeOfLuck
        aria-label: GitHub

  page-footer:
    center: "Sean Ryan"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
